os: linux
dist: trusty
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libbz2-dev
      - valgrind

env:
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" BUILD_TYPE=Debug BUILD_SHARED_LIBS=OFF
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" BUILD_TYPE=Release BUILD_SHARED_LIBS=OFF
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" BUILD_TYPE=Debug BUILD_SHARED_LIBS=ON
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" BUILD_TYPE=Release BUILD_SHARED_LIBS=ON

jobs:
  include:
    - env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      install:
        - make libraries
      script:
        - make
        - make tests

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - THIRD_PARTY=$HOME/third_party
  - THIRD_PARTY_PREFIX=$THIRD_PARTY/install
  - |
    mkdir -p $THIRD_PARTY && cd $THIRD_PARTY
    wget -qO- "http://zlib.net/zlib-1.2.11.tar.gz" | tar xz
    cd zlib-1.2.11
    mkdir build && cd build
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${THIRD_PARTY_PREFIX}
    make -j3 install
  - |
    mkdir -p $THIRD_PARTY && cd $THIRD_PARTY
    wget -qO- "http://www.nih.at/libzip/libzip-1.5.2.tar.gz" | tar xz
    cd libzip-1.5.2
    mkdir build && cd build
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${THIRD_PARTY_PREFIX} -DCMAKE_INSTALL_PREFIX=${THIRD_PARTY_PREFIX} -DENABLE_COMMONCRYPTO=OFF -DENABLE_GNUTLS=OFF -DENABLE_MBEDTLS=OFF
    make -j3 install
  - cd $TRAVIS_BUILD_DIR # Reset CWD

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_PREFIX_PATH=${THIRD_PARTY_PREFIX} -DCMAKE_INSTALL_PREFIX=$HOME/libzippp -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS
  - make -j3 install
  - make test
  - rm -r *
  - cmake ../tests/exampleProject -DCMAKE_PREFIX_PATH="${THIRD_PARTY_PREFIX};$HOME/libzippp" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make -j3
  - make test
  